---

- name: 1275776 - Installation saptune
  ansible.builtin.package:
    name: "saptune"

- name: "1275776 - Configuration saptune"
  ansible.builtin.command: "saptune daemon start"
  register: __sap_hana_preconfigure_register_saptune_daemon
  changed_when: __sap_hana_preconfigure_register_saptune_daemon.rc == 0
