---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Install ASCS
  include_tasks: install_ascs.yml
  when: GLOBAL_PRODUCT_TO_INSTALL == "ASCS"