---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Remove used credentials
  file:
    path: "{{ ascs_params_file_full_path }}"
    state: absent
  register: removal
  ignore_errors: yes

- name: Remove used credentials
  file:
    path: "{{ ers_params_file_full_path }}"
    state: absent
  register: removal
  ignore_errors: yes