---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Install JQ
  yum:
    name: jq
    state: present
  when: ansible_os_family == "RedHat"

- name: Install JQ
  apt:
    name: jq
    state: present
  when: ansible_os_family == "Debian"