---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Create directories if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ folders_to_create }}"