---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Common roles for preparing the image
- name: Check inputs, prepare logs, hostname, install basic dependencies and AWS Data Provider
  become: yes
  hosts: all
  roles:
    - role: ../shared-roles/check-inputs
      vars:
        input_variables_to_check: 
          - EC2_HOSTNAME
          - PRIVATE_DNS_ZONE
          - MASTER_PASSWORD
          - ASE_SID
          - SAPMNT_EFS_ID
          - S3_BUCKET_MEDIA_FILES
          - ENABLE_HA
          - AWS_CLI_PROFILE
    - role: ../shared-roles/common-os-tasks
    - role: ../shared-roles/prepare-logs-folders
    - role: ../shared-roles/set-hostname
      vars:
        extra_vars_to_add_to_hosts:
          - private_ip: "{{ GLOBAL_ASCS_PRIVATE_IP }}"
            hostname: "{{ GLOBAL_ASCS_HOSTNAME }}"
          - private_ip: "{{ GLOBAL_ASE_PRIVATE_IP }}"
            hostname: "{{ EC2_HOSTNAME }}"
          - private_ip: "{{ GLOBAL_PAS_PRIVATE_IP }}"
            hostname: "{{ GLOBAL_PAS_HOSTNAME }}"
    - role: ../shared-roles/install-pkg-mgr-dependencies
    - role: ../shared-roles/install-aws-sap-data-provider
    
# Installation-specific roles
- name: Set parameters and mount disks
  become: yes
  hosts: all
  roles:
    - role: ansible-role-parameters
    - role: ansible-role-disks

#  Roles for preparing for SAP Installation
- name: Prepare host with RedHat/SUSE certified roles
  become: yes
  hosts: all
  roles:
    - { role: ../shared-roles/sap-preconfigure-RedHat, when: ansible_os_family == "RedHat" }
    - role: ../shared-roles/sap-preconfigure-Suse
      vars:
        sap_preconfigure_saptune_solutions: ase 
      when: ansible_os_family == 'Suse'
      
# ASE installation roles
- name: ../shared-roles/Download and Install ASE
  become: yes
  hosts: all
  roles:
    - role: ansible-role-download-and-install