---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Fail if DB installation logs show errors on installation process
  stat:
    path: "{{ folder_to_run_db_installation_from }}/installationSuccesfullyFinished.dat"
  register: log_file_output
  failed_when: not log_file_output.stat.exists

