---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Ensure group "{{ sapinst_user_group_name }}" exists
  group:
    name: "{{ sapinst_user_group_name }}"
    gid: "{{ sap_inst_gid }}"
    state: present
    
- name: Add current user to "{{ sapinst_user_group_name }}" group
  user:
    name: "{{ ansible_user_id }}"
    group: "{{ sapinst_user_group_name }}"

- name: Ensure installation folders exist and have right permissions
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
    owner: "{{ ansible_user_id }}"
    group: "{{ sapinst_user_group_name }}"
    recurse: yes
  with_items:
    - "{{ swpm_sum_install_dest_folder }}"
    - "{{ folder_to_run_pas_installation_from }}"

- name: Ensure root user has root as primary group
  user:
    name: root
    group: root