---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- include_tasks: install_ssm_rhel.yml
  when: ansible_os_family == "RedHat"

- include_tasks: install_ssm_suse.yml
  when: ansible_os_family == "Suse"