---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Remove AWS CLI
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/usr/local/bin/aws"
    - "/usr/local/bin/aws_completer"
    - "/usr/local/aws-cli"